---
abstract: 'XRD Document Handling with Mojolicious'
author:
  - 'Nils Diewald'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.141170'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-XRD
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: '5.48'
  Mojolicious::Plugin::XML::Loy: '0.05'
  XML::Loy: '0.19'
  perl: '5.010001'
resources:
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: https://github.com/Akron/Mojolicious-Plugin-XRD
version: '0.11'
